#!/usr/bin/with-contenv bash
# shellcheck shell=bash

if [[ ! -f /config/feed2toot.ini ]]; then
    cp /defaults/feed2toot.ini /config/feed2toot.ini
fi

mkdir -p /config/creds /config/state
touch /config/hashtags.txt

# permissions
lsiown -R abc:abc \
    /config
